name: CI

permissions: read-all

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# Ensure that only a single job or workflow using the same
# concurrency group will run at a time. This would cancel
# any in-progress jobs in the same github workflow and github
# ref (e.g. refs/heads/main or refs/pull/<pr_number>/merge).
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: [self-hosted, zkir]
    steps:
      - name: Checkout ZKIR
        uses: actions/checkout@v4

      - name: Run `bazel test`
        run: |
          bazel --bazelrc=.bazelrc.ci test \
            --config ci \
            //...

  pre-commit-style:
    runs-on: [self-hosted, zkir]
    steps:
      - name: Checkout ZKIR
        uses: actions/checkout@v4

      - name: Checkout Setup Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: "3.10"

      - name: Install cpplint
        run: pip install cpplint

      # FIXME(ashjeong): clang-tidy currently fails on CI. See https://github.com/zk-rabbit/zkir/actions/runs/16904324348/job/47890440254 for more details.
      # - name: Refresh compile commands
      #   run: |
      #     bazel run --remote_cache=grpc://127.0.0.1:9092 @hedron_compile_commands//:refresh_all

      - name: Run pre-commit github action
        uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507 # pin@v3
